name: HaskellNixCabalStarter
version: '0.1.0.0'
author: HaskellNixCabalStarter
maintainer: HaskellNixCabalStarter
license: OtherLicense
dependencies:
- base >=4.12 && <4.13
- persistent
- persistent-sqlite
- persistent-postgresql
- persistent-template
- monad-logger
executables:
  app:
    source-dirs: src
    main: Main.hs
