version: '3'
services:
  adminer:
    image: "adminer"
    ports:
      - 8080:8080
  database:
    image: "postgres:alpine"
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./_data2/:/var/lib/postgresql/data
